// <auto-generated />
using System;
using GestionEnfermeria.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GestionEnfermeria.Migrations
{
    [DbContext(typeof(GestionEnfermeriaContext))]
    [Migration("20260429235309_m1")]
    partial class m1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GestionEnfermeria.Dominio.Asignar", b =>
                {
                    b.Property<int>("Id_Asignar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Asignar"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id_Enfermera")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Turno")
                        .HasColumnType("integer");

                    b.HasKey("Id_Asignar");

                    b.HasIndex("Id_Enfermera");

                    b.HasIndex("Id_Turno");

                    b.ToTable("Asignar");
                });

            modelBuilder.Entity("GestionEnfermeria.Dominio.Campo", b =>
                {
                    b.Property<int>("Id_Campo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Campo"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo_Campo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Campo");

                    b.ToTable("Campo");
                });

            modelBuilder.Entity("GestionEnfermeria.Dominio.Detalle_Seguimiento", b =>
                {
                    b.Property<int>("Id_Detalle_Seguimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Detalle_Seguimiento"));

                    b.Property<string>("Codigo_Receta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("Fecha_Final")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Fecha_Inicio")
                        .HasColumnType("date");

                    b.Property<int>("Id_Enfermera")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Seguimiento")
                        .HasColumnType("integer");

                    b.Property<string>("Observacion")
                        .HasColumnType("text");

                    b.HasKey("Id_Detalle_Seguimiento");

                    b.HasIndex("Id_Enfermera");

                    b.HasIndex("Id_Seguimiento");

                    b.ToTable("Detalle_Seguimiento");
                });

            modelBuilder.Entity("GestionEnfermeria.Dominio.Enfermera", b =>
                {
                    b.Property<int>("Id_Enfermera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Enfermera"));

                    b.Property<string>("Apellido_Materno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Apellido_Paterno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Codigo_Enfermera")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Enfermera");

                    b.ToTable("Enfermera");
                });

            modelBuilder.Entity("GestionEnfermeria.Dominio.Seguimiento", b =>
                {
                    b.Property<int>("Id_Seguimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Seguimiento"));

                    b.Property<string>("Codigo_Seguimiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Codigo_Seguro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado_Seguimiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Fecha_Final")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Fecha_Inicio")
                        .HasColumnType("date");

                    b.HasKey("Id_Seguimiento");

                    b.ToTable("Seguimiento");
                });

            modelBuilder.Entity("GestionEnfermeria.Dominio.Turno", b =>
                {
                    b.Property<int>("Id_Turno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Turno"));

                    b.Property<string>("Codigo_Turno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeOnly>("Hora_Final")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("Hora_Inicio")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Nombre_Turno")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Turno");

                    b.ToTable("Turno");
                });

            modelBuilder.Entity("GestionEnfermeria.Dominio.Turno_Campo", b =>
                {
                    b.Property<int>("Id_Turno_Campo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Turno_Campo"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id_Campo")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Turno")
                        .HasColumnType("integer");

                    b.HasKey("Id_Turno_Campo");

                    b.HasIndex("Id_Campo");

                    b.HasIndex("Id_Turno");

                    b.ToTable("Turno_Campo");
                });

            modelBuilder.Entity("GestionEnfermeria.Dominio.Asignar", b =>
                {
                    b.HasOne("GestionEnfermeria.Dominio.Enfermera", "Enfermera")
                        .WithMany("Asignar")
                        .HasForeignKey("Id_Enfermera")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionEnfermeria.Dominio.Turno", "Turno")
                        .WithMany("Asignar")
                        .HasForeignKey("Id_Turno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enfermera");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("GestionEnfermeria.Dominio.Detalle_Seguimiento", b =>
                {
                    b.HasOne("GestionEnfermeria.Dominio.Enfermera", "Enfermera")
                        .WithMany("Detalle_Seguimiento")
                        .HasForeignKey("Id_Enfermera")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionEnfermeria.Dominio.Seguimiento", "Seguimiento")
                        .WithMany("Detalle_Seguimiento")
                        .HasForeignKey("Id_Seguimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enfermera");

                    b.Navigation("Seguimiento");
                });

            modelBuilder.Entity("GestionEnfermeria.Dominio.Turno_Campo", b =>
                {
                    b.HasOne("GestionEnfermeria.Dominio.Campo", "Campo")
                        .WithMany("Turno_Campo")
                        .HasForeignKey("Id_Campo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionEnfermeria.Dominio.Turno", "Turno")
                        .WithMany("Turno_Campo")
                        .HasForeignKey("Id_Turno")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campo");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("GestionEnfermeria.Dominio.Campo", b =>
                {
                    b.Navigation("Turno_Campo");
                });

            modelBuilder.Entity("GestionEnfermeria.Dominio.Enfermera", b =>
                {
                    b.Navigation("Asignar");

                    b.Navigation("Detalle_Seguimiento");
                });

            modelBuilder.Entity("GestionEnfermeria.Dominio.Seguimiento", b =>
                {
                    b.Navigation("Detalle_Seguimiento");
                });

            modelBuilder.Entity("GestionEnfermeria.Dominio.Turno", b =>
                {
                    b.Navigation("Asignar");

                    b.Navigation("Turno_Campo");
                });
#pragma warning restore 612, 618
        }
    }
}
